//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.Shared.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Catalog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Catalog() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vanilla.Shared.Resources.Localization.Catalog", typeof(Catalog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Leilão.
        /// </summary>
        internal static string AUCTION_FIELD_VALIDATION {
            get {
                return ResourceManager.GetString("AUCTION_FIELD_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro na requisição do servidor!.
        /// </summary>
        internal static string BAD_REQUEST_MESSAGE {
            get {
                return ResourceManager.GetString("BAD_REQUEST_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o comprador.
        /// </summary>
        internal static string BUYER_FIELD_VALIDATION {
            get {
                return ResourceManager.GetString("BUYER_FIELD_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o CNPJ.
        /// </summary>
        internal static string CNPJ_FIELD_VALIDATION1 {
            get {
                return ResourceManager.GetString("CNPJ_FIELD_VALIDATION1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a descrição.
        /// </summary>
        internal static string DESCRIPTION_FIELD_VALIDATION {
            get {
                return ResourceManager.GetString("DESCRIPTION_FIELD_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe esse email cadastrado!.
        /// </summary>
        internal static string EMAIL_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("EMAIL_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o email corretamente.
        /// </summary>
        internal static string EMAIL_FIELD_VALIDATION {
            get {
                return ResourceManager.GetString("EMAIL_FIELD_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o email deve ser um email válido.
        /// </summary>
        internal static string EMAIL_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o email não pode ser em branco.
        /// </summary>
        internal static string EMAIL_ISNULL_OR_EMPTY {
            get {
                return ResourceManager.GetString("EMAIL_ISNULL_OR_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de início deve ser menor que a data de término.
        /// </summary>
        internal static string END_DATE_FIELD_VALIDATION {
            get {
                return ResourceManager.GetString("END_DATE_FIELD_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe essa empresa cadastrada!.
        /// </summary>
        internal static string ENTERPRISE_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("ENTERPRISE_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao processar no servidor!.
        /// </summary>
        internal static string ERROR_SERVER_MESSAGE {
            get {
                return ResourceManager.GetString("ERROR_SERVER_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o primeiro nome.
        /// </summary>
        internal static string FIRST_NAME_FIELD_VALIDATION {
            get {
                return ResourceManager.GetString("FIRST_NAME_FIELD_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o sobrenome.
        /// </summary>
        internal static string LAST_NAME_FIELD_VALIDATION {
            get {
                return ResourceManager.GetString("LAST_NAME_FIELD_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail ou nome inválido.
        /// </summary>
        internal static string LOGIN_EXCEPTION {
            get {
                return ResourceManager.GetString("LOGIN_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário o ponto de medição.
        /// </summary>
        internal static string METERING_POINT_FIELD_VALIDATION {
            get {
                return ResourceManager.GetString("METERING_POINT_FIELD_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe esse nome cadastrado!.
        /// </summary>
        internal static string NAME_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("NAME_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o nome.
        /// </summary>
        internal static string NAME_FIELD_VALIDATION {
            get {
                return ResourceManager.GetString("NAME_FIELD_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processado com sucesso!.
        /// </summary>
        internal static string OK_MESSAGE {
            get {
                return ResourceManager.GetString("OK_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a senha baseado na regra de senha.
        /// </summary>
        internal static string PASSWORD_FIELD_VALIDATION {
            get {
                return ResourceManager.GetString("PASSWORD_FIELD_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a senha não pode ser em branco.
        /// </summary>
        internal static string PASSWORD_ISNULL_OR_EMPTY {
            get {
                return ResourceManager.GetString("PASSWORD_ISNULL_OR_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuperação de senha.
        /// </summary>
        internal static string PASSWORD_RECOVERY {
            get {
                return ResourceManager.GetString("PASSWORD_RECOVERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o usuário.
        /// </summary>
        internal static string USER_FIELD_VALIDATION {
            get {
                return ResourceManager.GetString("USER_FIELD_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the user group.
        /// </summary>
        internal static string USER_GROUP_FIELD_VALIDATION {
            get {
                return ResourceManager.GetString("USER_GROUP_FIELD_VALIDATION", resourceCulture);
            }
        }
    }
}
